core/urls.py
from django.conf.urls import url

from . import views

# Application Routes (URLs)

app_name = "core"

urlpatterns = [
    # Login
    url(r"^login/$", views.login, name="login"),
    # Logout
    url(r"^logout/$", views.logout, name="logout"),
    # Register
    url(r"^register/$", views.register, name="register"),
]

voting/urls.py
from django.conf.urls import url, include

from . import views

# Application Routes (URLs)

app_name = "voting"

urlpatterns = [
    # General Page Views
    url(r"^$", views.homepage_view, name="homepage"),
    url(r"^add-poll$", views.add_poll, name="add_poll"),
    url(r"^delete-poll/(?P<pk>\d+)/$", views.DeletePollView.as_view(), name="delete_poll"),
    url(r"^poll-alert/(?P<pk>\d+)/$", views.poll_alert, name="poll_alert"),
    url(r"^vote/(?P<result>\d+)/poll/(?P<poll>\d+)/$", views.vote_view, name="vote"),
]

voting/models.py
from django.db import models

from django.contrib.auth.models import User

name_length = 100
url_length = 300


# Create your models here.
class Poll(models.Model):
    title = models.CharField(max_length=name_length)
    url = models.CharField(max_length=url_length)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_votes(self):
        return Vote.objects.filter(poll=self)


# Create your models here.
class Vote(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    is_yes = models.BooleanField()

voting/forms.py
from django import forms

from .models import Poll


class AddPollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['title', 'url']

voting/views.py
from django.shortcuts import render, redirect

from django.core.mail import send_mail

from django.contrib.auth.models import User

from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.utils.decorators import method_decorator

from django.views.generic.edit import DeleteView, UpdateView, CreateView

from marketing.utils import get_class_based_default_context

from .models import Poll, Vote
from .forms import AddPollForm


@login_required
# Create your views here.
def homepage_view(request):
    context = {
        "polls": Poll.objects.all(),
        "form": AddPollForm()
    }
    return render(request, 'voting/voting.html', context)


@login_required
def vote_view(request, result, poll):
    try:
        v = Vote.objects.get(poll__pk=poll, user=request.user)
        v.is_yes = bool(int(result))
        v.save()
        messages.success(request, 'Your vote has been changed!')
    except Exception as e:
        Vote.objects.create(
            user=request.user, poll=Poll.objects.get(pk=poll), is_yes=bool(result)
        )
        messages.success(request, 'Your vote has been recorded!')
    return redirect('voting:homepage')


@login_required
def add_poll(request):
    context = {}
    if request.method == "POST":
        form = AddPollForm(request.POST)
        if form.is_valid():
            form.instance.creator = request.user
            form.save()
            return redirect('voting:homepage')
        else:
            context['form'] = form
            context['polls'] = Poll.objects.all()
    return render(request, 'voting/voting.html', context)


@login_required
def poll_alert(request, pk):
    try:
        poll = Poll.objects.get(pk=pk)
        send_mail(
            'Vote Now In Marketing Management',
            '{0} has requested you vote on the poll: {1}. Vote now: http://mm.techandmech.com/voting'.format(request.user, str(poll)),
            'webmaster@mm.techandmech.com',
            User.objects.all().values_list('email', flat=True),
            fail_silently=False,
        )
        messages.success(request, 'Users have been notified to vote on the poll!')
    except Exception as e:
        print(str(e))
    return redirect('voting:homepage')


@method_decorator(login_required, name="dispatch")
class DeletePollView(DeleteView):
    model = Poll
    success_url = "/voting"

    def get_context_data(self, **kwargs):
        return get_class_based_default_context(
            super().get_context_data(**kwargs),
            self.request.user
        )

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Poll deleted!")
        return super(DeletePollView, self).delete(*args, **kwargs)

voting/templates/voting/poll_confirm_delete.html
{% extends 'website/base.html' %}

{% block content %}
<!-- main page row -->
<div class="row">
    <div class="col-6">
      <div class="card image-card" style="padding-bottom:15px;">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete the poll "{{ object }}"?</p>
            <a href="{%  url 'voting:homepage' %}">(Cancel)</a>
            <input type="submit" value="Confirm">
        </form>
      </div>
    </div>
</div>
<!--  End main page row -->
{% endblock content %}

voting/templates/voting/voting.html
{% extends 'website/base.html' %}

{% block custom_css %}
input {
  border-radius:50px;
  border: 2px solid #aaa;
  padding: 5px 10px 5px 10px;
  width:100%;
}

.fa-trash-alt, .fa-bell {
  text-size: 10px;
  margin-left: 2px;
}

.link-icon {
  color: black;
}
{% endblock custom_css %}

{% block content %}
<div class="row">
  <div class="col" style="padding-right:50px;">
    <div class="row">
      <div class="col-3">
        <h2>Active Polls</h2>
      </div>
      <div class="col">
        <input id="polls-search" type="text" placeholder="Search Polls...">
      </div>
    </div>
    <br>
    <div class="card">
      <div class="row">
        <div class="col-9">
          <h6>TITLE</h6>
          <hr>
        </div>
        <div class="col-1 text-center">
          <h6>URL</h6>
          <hr>
        </div>
        <div class="col text-center">
          <h6>VOTE</h6>
          <hr>
        </div>
      </div>
      {% for poll in polls %}
        <div class="row">
          <div class="col-9">
            {{ poll }}
            <a href="{% url 'voting:poll_alert' pk=poll.pk %}" style="color:black;">
              <i class="fas fa-bell animated item"></i>
            </a>
            <a href="{% url 'voting:delete_poll' pk=poll.pk %}" style="color:black;">
              <i class="fas fa-trash-alt animated item"></i>
            </a>
            <br>
            <p style="font-weight:300;font-size:12px;color:#aaa;">
              {% if poll.get_votes %}
                (
                  {% for vote in poll.get_votes %}
                    {{ vote.user }} |
                    {% if vote.is_yes %}
                    Y
                    {% else %}
                    N
                    {% endif %},
                  {% endfor %}
                )
              {% endif %}
            </p>
          </div>
          <div class="col-1 text-center">
            <a href="{{ poll.url }}" style="color:black;" target="_blank" rel="noopener noreferrer">
              <i class="fas fa-link"></i>
            </a>
          </div>
          <div class="col text-center">
            <div class="row">
              <div class="col">
                <button type="button" class="btn btn-danger action-link" href="{% url 'voting:vote' result=0 poll=poll.pk %}">N</button>
                <button type="button" class="btn btn-success action-link" href="{% url 'voting:vote' result=1 poll=poll.pk %}">Y</button>
              </div>
            </div>
          </div>
        </div>
        <hr>
      {% empty %}
        <div class="row">
          <div class="col">There are currently no active polls.</div>
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="col">
    <h2>Create A Poll</h2>
    <br>
    <div class="card">
      <form action="{% url 'voting:add_poll' %}" method="post">{% csrf_token %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
          {% endfor %}
          {{ field.label }}<br>
          {{ field }}<br><br>
        {% endfor %}
        <div class="row text-center">
          <div class="col">
            <button type="submit" class="btn btn-success text-center">Create Poll</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}