core/urls.py
from django.conf.urls import url

from . import views

# Application Routes (URLs)

app_name = "core"

urlpatterns = [
    # Login
    url(r"^login/$", views.login, name="login"),
    # Logout
    url(r"^logout/$", views.logout, name="logout"),
    # Register
    url(r"^register/$", views.register, name="register"),
]

marketing/urls.py
from django.conf.urls import url, include

from . import views

app_name = "marketing"

urlpatterns = [
    url(r"^$", views.homepage_view, name="homepage"),

    url(r"^add-project$", views.CreateProjectView.as_view(), name="add_project"),
    url(r"^set-current-project/(?P<pk>\d+)/$", views.set_current_project_view, name="set_current_project"),

    url(r"^add-location$", views.CreateLocationView.as_view(), name="add_location"),
    url(r"^locations$", views.locations_view, name="locations"),
    url(r"^delete-location/(?P<pk>\d+)/$", views.DeleteLocationView.as_view(), name="delete_location"),
    url(r"^view-location/(?P<pk>\d+)/$", views.ViewLocationDetailView.as_view(), name="view_location"),

    # url(r"^add-sample-post$", views.CreateSamplePostView.as_view(), name="add_sample_post"),
    url(r"^sample-posts$", views.sample_posts_view, name="sample_posts"),
    url(r"^add-sample-posts$", views.CreateSamplePostView.as_view(), name="add_sample_post"),
    url(r"^delete-sample-post/(?P<pk>\d+)/$", views.DeleteSamplePostView.as_view(), name="delete_sample_post"),
    url(r"^view-sample-post/(?P<pk>\d+)/$", views.ViewSamplePostDetailView.as_view(), name="view_sample_post"),

    url(r"^live-posts$", views.live_posts_view, name="live_posts"),
    url(r"^create-live-post/(?P<pk>\d+)/$", views.CreateLivePostView.as_view(), name="create_live_post"),
    url(r"^mark-post-inactive/(?P<pk>\d+)/$", views.mark_post_inactive, name="mark_post_inactive"),
    url(r"^delete-live-post/(?P<pk>\d+)/$", views.DeleteLivePostView.as_view(), name="delete_live_post"),

    url(r"^resources$", views.resources_view, name="resources"),
    url(r"^add-resource$", views.CreateResourceView.as_view(), name="add_resource"),
    url(r"^delete-resource/(?P<pk>\d+)/$", views.DeleteResourceView.as_view(), name="delete_resource"),
    url(r"^view-resource/(?P<pk>\d+)/$", views.ViewResourceDetailView.as_view(), name="view_resource"),

    url(r"^tasks$", views.tasks_view, name="tasks"),

    url(r"^assign-post-task$", views.CreatePostingTaskView.as_view(), name="add_posting_task"),
    url(r"^mark-post-task-complete/(?P<pk>\d+)/$", views.mark_post_task_complete, name="mark_post_task_complete"),
    url(r"^delete-create-post-task/(?P<pk>\d+)/$", views.DeleteCreatePostTaskView.as_view(), name="delete_create_post_task"),
    url(r"^view-post-task/(?P<pk>\d+)/$", views.ViewPostTaskDetailView.as_view(), name="view_posting_task"),

    url(r"^assign-monitor-task$", views.CreateMonitoringTaskView.as_view(), name="add_monitoring_task"),
    url(r"^mark-monitor-task-complete/(?P<pk>\d+)/$", views.mark_monitor_task_complete, name="mark_monitor_task_complete"),
    url(r"^delete-monitor-post-task/(?P<pk>\d+)/$", views.DeleteMonitorPostTaskView.as_view(), name="delete_monitor_post_task"),
    url(r"^view-monitor-task/(?P<pk>\d+)/$", views.ViewMonitorTaskDetailView.as_view(), name="view_monitor_task"),
]

marketing/models.py
from django.db import models

from datetime import datetime

from django.contrib.auth.models import User

name_length = 50
abbreviated_name_length = 10
description_length = 150
url_length = 300

TYPE_CHOICES = (
    ('I', 'Image'),
    ('D', 'Document'),
    ('M', 'Misc'),
)


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=name_length)
    abbreviated_name = models.CharField(max_length=abbreviated_name_length)
    people = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class CurrentProject(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Platform(models.Model):
    name = models.CharField(max_length=name_length)
    abbreviated_name = models.CharField(max_length=abbreviated_name_length)

    def __str__(self):
        return self.name


class Location(models.Model):
    name = models.CharField(max_length=name_length)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    platform = models.ForeignKey(Platform, on_delete=models.CASCADE)
    url = models.CharField(max_length=url_length)
    description = models.CharField(max_length=description_length)
    posts_per_week = models.PositiveIntegerField(default=0)
    following_count = models.PositiveIntegerField(default=0)
    tone = models.CharField(max_length=50)
    notes = models.CharField(max_length=500, blank=True, null=True)

    class Meta:
        ordering = ['platform', 'name']

    def __str__(self):
        return self.name + " (" + self.platform.abbreviated_name + ")"

    def get_posts(self):
        return LivePost.objects.filter(location=self)

    def get_sales(self):
        posts = self.get_posts()
        sales = 0
        for post in posts:
            sales += post.get_sales()
        return sales


class Resource(models.Model):
    name = models.CharField(max_length=name_length)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    url = models.CharField(max_length=url_length)
    notes = models.CharField(max_length=500, blank=True, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_posts_used_in(self):
        return SamplePost.objects.filter(resources__pk=self.pk)


class SamplePost(models.Model):
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    caption = models.CharField(max_length=500)
    title = models.CharField(max_length=description_length)
    tags = models.CharField(max_length=description_length)
    resources = models.ManyToManyField(Resource)
    notes = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_live_posts(self):
        return LivePost.objects.filter(sample_post=self)

    def get_num_total_likes(self):
        related_posts_likes = self.get_live_posts().values_list('number_of_likes', flat=True)
        return sum(list(related_posts_likes))

    def get_num_total_comments(self):
        related_posts_comments = self.get_live_posts().values_list('number_of_comments', flat=True)
        return sum(list(related_posts_comments))

    def get_num_total_shares(self):
        related_posts_shares = self.get_live_posts().values_list('number_of_shares', flat=True)
        return sum(list(related_posts_shares))


class LivePost(models.Model):
    is_active = models.BooleanField(default=True)
    poster = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    code = models.CharField(max_length=50, null=True, blank=True)
    sample_post = models.ForeignKey(SamplePost, on_delete=models.CASCADE)
    number_of_likes = models.PositiveIntegerField(default=0)
    number_of_shares = models.PositiveIntegerField(default=0)
    number_of_comments = models.PositiveIntegerField(default=0)
    post_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.sample_post.title

    def get_sales(self):
        return 50

    def get_number_of_interactions(self):
        return (self.number_of_likes + self.number_of_shares + self.number_of_comments)


class MonitorTask(models.Model):
    completed = models.BooleanField(default=False)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='monitor_task_creator')
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='monitor_task_assigned_to')
    live_post = models.ForeignKey(LivePost, null=True, blank=True, on_delete=models.CASCADE)
    due_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return "Monitor | {0}".format(str(self.live_post))

    def is_overdue(self):
        return self.due_date < datetime.now().date()


class CreatePostTask(models.Model):
    completed = models.BooleanField(default=False)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_task_creator')
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_task_assigned_to')
    locations = models.ManyToManyField(Location)
    sample_post = models.ForeignKey(SamplePost, null=True, blank=True, on_delete=models.CASCADE)
    due_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return "Publish Post | {0}".format(self.sample_post)


class Webstore(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    private_api_key = models.CharField(max_length=150)
    public_api_key = models.CharField(max_length=150)

marketing/templates/marketing/createposttask_form.html
{% extends 'website/base.html' %}

{% block content %}
<style type="text/css">
  input, select {
    width: 100%;
  }
  #id_create_post {
    margin-top: 10px;
    font-size: 25px;
    width: 25px;
    height: 25px;
  }
</style>

<!-- main page row -->
<div class="row">

  <!-- Page title -->
  <div class="col-12 top-bar text-center">
    <div class="row">

      <div class="col">
        <h2>Create a Task</h2>
      </div>

    </div>
  </div>
  <!-- End Page title -->

  <!-- Add Project Form -->
  <div class="col-lg-6 offset-lg-3">
    <div class="card">
      <form  action="{% url 'marketing:add_posting_task' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
          {% for error in form.field.errors %}
          {% endfor %}
          {{ field.label }} <br>
          {{ field }} <br><br>
        {% endfor %}
        <input type="submit" name="submit" value="Submit" class="btn btn-success">
      </form>
    </div>
  </div>
  <!-- End Add Project Form -->

</div>
<!--  End main page row -->
{% endblock content %}

marketing/templates/marketing/monitortask_detail.html
{% extends 'website/base.html' %}

{% block custom_css %}

{% endblock custom_css %}

{% block content %}
<!-- main page row -->
<div class="row">

  <div class="col-8">

    <!-- Assign to user card -->
    <div class="card" style="padding-bottom:15px;">
      <span>
        <i class="fas fa-comment-dots card-icon" style="background-color:var(--in-progress-color);"></i>
        <text class="card-heading">Monitor Post</text>
        <button type="button" class="btn btn-success btn-sm action-link up" href="{% url 'marketing:mark_monitor_task_complete' pk=object.pk %}">Mark Complete</button>
      </span>
      <br>
      <!-- card inner row -->
      <div class="row">

        <div class="col">

          <!-- Locations Headings -->
          <div class="row">
            <div class="col">
              <h6>Project</h6>
              <hr>
            </div>
            <div class="col-8">
              <h6>Post</h6>
              <hr>
            </div>
          </div>
          <!-- End Locations Headings -->

          <div class="row">
            <div class="col">
              {{ object.live_post.sample_post.project }}
            </div>
            <div class="col-8">
              <a href="#">{{ object.live_post }}</a>
            </div>
          </div>

        </div>

      </div>
      <!-- end card inner row -->
    </div>


  </div>

  <div class="col">
    <div class="card">
      <span>
        <i class="fas fa-pencil-alt card-icon" style="background-color:black;"></i>
        <text class="card-heading">General Notes</text>
        <br><br>
        <ul>
          {% for note in object.get_notes %}
            <li>{{ note }}</li>
          {% empty %}
            <li>There are not notes at this time.</li>
          {% endfor %}
        </ul>
      </span>
    </div>
  </div>

</div>

<div class="row">
  <div class="col">
      <div class="card">
        <span>
          <i class="fas fa-globe card-icon"></i>
          <text class="card-heading">Location To Monitor</text>
        </span>
        <br>
        <div class="row">
          <div class="col">
            <h6>Name/Link</h6>
            <hr>
          </div>
          <div class="col">
            <h6>Platform</h6>
            <hr>
          </div>
          <div class="col">
            <h6>Notes</h6>
            <hr>
          </div>
          <div class="col">
            <h6>Interact</h6>
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col">
            {{ object.live_post.location }}
            <a href="#" style="margin-left:5px;color:black;">
              <i class="fas fa-link" href="{% url 'marketing:view_location' pk=object.live_post.location.pk %}"></i>
            </a>
          </div>
          <div class="col">
            {{ object.live_post.location.platform }}
          </div>
          <div class="col">
            {% for note in location.get_notes %}
              {{ note }}<br>
            {% endfor %}
          </div>
          <div class="col">
            <a class="btn btn-success btn-xs" href="http://localhost:8000/admin/marketing/livepost/{{object.live_post.pk}}/change/" target="_blank" rel="noopener noreferrer">Record Details</a>
          </div>
        </div>
      </div>
  </div>
</div>
<!--  End main page row -->
{% endblock content %}

marketing/templates/marketing/resource_detail.html
{% extends 'website/base.html' %}

{% block custom_css %}
.preview {
  width: 400px;
}
{% endblock custom_css %}

{% block content %}
<!-- main page row -->
<div class="row">

  <div class="col-8">

    <!-- Assign to user card -->
    <div class="card" style="padding-bottom:15px;">
      <span>
        <i class="fas fa-comment-dots card-icon" style="background-color:var(--in-progress-color);"></i>
        <text class="card-heading">
          {{ object }}
          <i class="fas fa-link action-link" href="{{ object.url }}"></i>
        </text>
      </span>
      <br>
      <!-- card inner row -->
      <div class="row">

        <div class="col">

          <div class="row">
            <div class="col">
              <h6>Type</h6>
              <hr>
            </div>
            <div class="col">
              <h6>Creator</h6>
              <hr>
            </div>
          </div>

          <div class="row">
            <div class="col">
              {{ object.get_type_display }}
            </div>
            <div class="col">
              {{ object.creator }}
            </div>
          </div>

        </div>

      </div>
      <!-- end card inner row -->
    </div>


  </div>

  <div class="col">
    <div class="card">
      <span>
        <i class="fas fa-pencil-alt card-icon" style="background-color:black;"></i>
        <text class="card-heading">General Notes</text>
        <br><br>
        <ul>
          {% for note in object.get_notes %}
            <li>{{ note }}</li>
          {% empty %}
            <li>There are not notes at this time.</li>
          {% endfor %}
        </ul>
      </span>
    </div>
  </div>

</div>

<div class="row">
  <div class="col-8">
      <div class="card">
        <span>
          <i class="fas fa-image card-icon" style="background-color:pink;"></i>
          <text class="card-heading">Preview</text>
        </span>
        <br>
        <div class="row">
          <div class="col">
            {% if object.type == "I" %}
              <img src="{{ object.url }}" class="preview"/>
            {% else %}
            {% endif %}
          </div>
        </div>
      </div>
  </div>
  <div class="col">
    <div class="card">
      <span>
        <i class="fas fa-sticky-note card-icon"></i>
        <text class="card-heading">Posts</text>
      </span>
      <br>
      {% for post in object.get_posts_used_in %}
       <a href="{% url 'marketing:view_sample_post' pk=post.pk %}">{{ post }}</a> <br>
      {% empty %}
        This resource is not used in any posts.
      {% endfor %}
    </div>
  </div>
</div>
<!--  End main page row -->
{% endblock content %}

marketing/templates/marketing/sample_posts.html
{% extends 'website/base.html' %}

{% block content %}
<!-- main page row -->
<div class="row">

  <!-- Page title and filter bar -->
  <div class="col-12 top-bar">
    <div class="row">

      <div class="col-2">
        <h2>Sample Posts</h2>
      </div>

    </div>
  </div>
  <!-- End Page title and filter bar -->

  {% for post in sample_posts %}
  <!-- Locations -->
  <div class="col-6">
      <!-- Location Card -->
      <div class="card" style="padding-bottom:15px;">
        <span>
          <i class="fas fa-sticky-note card-icon"></i>
          <text class="card-heading">{{ post }}</text>
          <i class="fas fa-pencil-alt action-link animated item" href="#"></i>
          <i class="fas fa-trash-alt action-link animated item" href="{% url 'marketing:delete_sample_post' pk=post.pk %}"></i>
          <i class="fas fa-link action-link animated item" href="{% url 'marketing:view_sample_post' pk=post.pk %}"></i>
          <button type="button" name="button" class="btn btn-primary up action-link" href="{% url 'marketing:create_live_post' pk=post.pk %}">Create Live Post</button>
        </span>
        <br>
        <!-- card inner row -->
        <div class="row">
          <div class="col">

            <!-- Locations Headings -->
            <div class="row">
              <div class="col">
                <h6>Created By</h6>
                <hr>
              </div>
              <div class="col-3">
                <h6>Project</h6>
                <hr>
              </div>
              <div class="col-5">
                <h6>Tags</h6>
                <hr>
              </div>
            </div>
            <!-- End Locations Headings -->

            <!-- Sample Posts -->
            <div class="row">
              <div class="col">
                {{ post.creator }}
              </div>
              <div class="col-3">
                {{ post.project }}
              </div>
              <div class="col-5">
                {{ post.tags }}
              </div>
            </div>
            <!-- End Sample Posts -->

          </div>
        </div>
        <!-- end card inner row -->
      </div>
      <!-- End Location Card -->

  </div>
  {% endfor %}
  <!-- End Locations -->

</div>
<!--  End main page row -->
{% endblock content %}

marketing/templates/marketing/samplepost_detail.html
{% extends 'website/base.html' %}

{% block custom_css %}
.preview {
  width: 400px;
}
{% endblock custom_css %}

{% block content %}
<!-- Details and Notes -->
<div class="row">

  <div class="col-8">

    <!-- Assign to user card -->
    <div class="card" style="padding-bottom:15px;">
      <span>
        <i class="fas fa-sticky-note card-icon"></i>
        <text class="card-heading">
          {{ object }}
        </text>
      </span>
      <br>
      <!-- card inner row -->
      <div class="row">

        <div class="col">

          <div class="row">
            <div class="col">
              <h6>Creator</h6>
              <hr>
            </div>
            <div class="col">
              <h6>Tags</h6>
              <hr>
            </div>
            <div class="col">
              <h6># Likes</h6>
              <hr>
            </div>
            <div class="col">
              <h6># Comments</h6>
              <hr>
            </div>
            <div class="col">
              <h6># Shares</h6>
              <hr>
            </div>
          </div>
          <div class="row">
            <div class="col">
              {{ object.creator }}
            </div>
            <div class="col">
              {{ object.tags }}
            </div>
            <div class="col">
              {{ object.get_num_total_likes }}
            </div>
            <div class="col">
              {{ object.get_num_total_comments }}
            </div>
            <div class="col">
              {{ object.get_num_total_shares }}
            </div>
          </div>

        </div>

      </div>
      <!-- end card inner row -->
    </div>


  </div>

  <div class="col">
    <div class="card">
      <span>
        <i class="fas fa-pencil-alt card-icon" style="background-color:black;"></i>
        <text class="card-heading">General Notes</text>
        <br><br>
        <p>{{ object.notes }}</p>
      </span>
    </div>
  </div>

</div>

<!-- Resources Used -->
<div class="row">
  <div class="col">
      <div class="card">
        <span>
          <i class="fas fa-wrench card-icon"></i>
          <text class="card-heading">Resources</text>
        </span>
        <br>
        <div class="row">
          <div class="col">
            <h6>Name</h6>
            <hr>
          </div>
          <div class="col">
            <h6>Type</h6>
            <hr>
          </div>
          <div class="col">
            <h6>URL</h6>
            <hr>
          </div>
          <div class="col-6">
            <h6>Notes</h6>
            <hr>
          </div>
        </div>
        {% for resource in object.resources.all %}
          <div class="row">
            <div class="col">
              {{ resource }}
              <i class="fas fa-link action-link" href="{% url 'marketing:view_resource' pk=resource.pk %}"></i>
            </div>
            <div class="col">
              {{ resource.get_type_display }}
            </div>
            <div class="col">
              <a href="{{ resource.url }}">(click here)</a>
            </div>
            <div class="col-6">
              {% for note in resource.get_notes %}
              {% endfor %}
            </div>
          </div>
        {% endfor %}
      </div>
  </div>
</div>

<!-- Active Locations -->
<div class="row">
  <div class="col">
      <div class="card">
        <span>
          <i class="fas fa-globe card-icon"></i>
          <text class="card-heading">Active Locations</text>
        </span>
        <br>
        <div class="row">
          <div class="col-2">
            <h6>Location</h6>
            <hr>
          </div>
          <div class="col">
            <h6>Tone</h6>
            <hr>
          </div>
          <div class="col-4">
            <h6>Notes</h6>
            <hr>
          </div>
          <div class="col">
            <h6>Earned</h6>
            <hr>
          </div>
          <div class="col">
            <h6># Likes</h6>
            <hr>
          </div>
          <div class="col">
            <h6># Comments</h6>
            <hr>
          </div>
          <div class="col">
            <h6># Shares</h6>
            <hr>
          </div>
        </div>
        {% for live_post in object.get_live_posts %}
          <div class="row">
            <div class="col-2">
              {{ live_post.location }}
              <i class="fas fa-link action-link" href="{% url 'marketing:view_location' pk=live_post.location.pk %}"></i>
            </div>
            <div class="col">
              {{ live_post.location.tone }}
            </div>
            <div class="col-4">
              {{ live_post.location.notes }}
            </div>
            <div class="col">
              <text class="financial-data">${{ live_post.get_sales }}</text>
            </div>
            <div class="col">
              {{ live_post.number_of_likes }}
            </div>
            <div class="col">
              {{ live_post.number_of_comments}}
            </div>
            <div class="col">
              {{ live_post.number_of_shares }}
            </div>
          </div>
        {% endfor %}
      </div>
  </div>
</div>
<!--  End main page row -->
{% endblock content %}

marketing/templates/marketing/tasks.html
{% extends 'website/base.html' %}

{% block custom_css %}
.up {
  margin-top: -8px !important;
}

.up:nth-child(odd) {
  margin-left: 10px;

}

.interactable:hover {
  background-color: #f2f3f4;
}
{% endblock custom_css %}

{% block content %}
<!-- main page row -->

<div class="row">
  <div class="col">
    <button type="button" name="False" class="btn btn-primary up action-link assigned-to" href="{% url 'marketing:tasks' %}">View All</button>
    <button type="button" name="False" class="btn btn-default up assigned-to" style="margin-left:10px;">In-Progress</button>
    <button type="button" name="True" class="btn btn-default up assigned-to">Complete</button>
  </div>
</div>

<br>

<div class="row">

  <div class="col">

    <!-- Assign to user card -->
    <div class="card" style="padding-bottom:15px;">
      <span>
        <i class="fas fa-spinner card-icon" style="background-color:var(--in-progress-color);"></i>
        <text class="card-heading">Assigned to You</text>

      </span>
      <br>
      <!-- card inner row -->
      <div class="row">
        <div class="col">

          <!-- Tasks Headings -->
          <div class="row">
            <div class="col-2">
              <h6>Project</h6>
              <hr>
            </div>
            <div class="col-3">
              <h6>Post</h6>
              <hr>
            </div>
            <div class="col">
              <h6>Due Date</h6>
              <hr>
            </div>
            <div class="col">
              <h6>Type</h6>
              <hr>
            </div>
            <div class="col">
              <h6>Assigned By</h6>
              <hr>
            </div>
            <div class="col">
              <h6>Due Date / Interact</h6>
              <hr>
            </div>
          </div>
          <!-- End Tasks Headings -->

          {% for task in tasks.to_user %}
          {% if task.sample_post %}
            <div class="row interactable action-link" href="{% url 'marketing:view_posting_task' pk=task.pk %}">
              <div class="col-2 item-container {{task.completed}}">
                  {{ task.sample_post.project }}
              </div>
              <div class="col-3 item-container {{task.completed}}">
                {{ task.sample_post.title }}
                <i class="fas fa-link action-link" href="{% url 'marketing:view_sample_post' pk=task.sample_post.pk %}"></i>
              </div>
              <div class="col item-container {{task.completed}}">
                {{ task.due_date }}
              </div>
              <div class="col item-container {{task.completed}}">
                  CREATE POST
              </div>
              <div class="col item-container {{task.completed}}">
                {{ task.creator }}
              </div>
              <div class="col item-container {{task.completed}}">
                {{ task.due_date }}
              </div>
            </div>
          {% else %}
            <div class="row interactable action-link" href="{% url 'marketing:view_monitor_task' pk=task.pk %}">
              <div class="col-2 item-container {{task.completed}}">
                {{ task.live_post.sample_post.project }}
              </div>
              <div class="col-3 item-container {{task.completed}}">
                {{ task.live_post.sample_post.title }}
                <i class="fas fa-link action-link" href="{% url 'marketing:view_sample_post' pk=task.live_post.sample_post.pk %}"></i>
              </div>
              <div class="col item-container {{task.completed}}">
                {{ task.due_date }}
              </div>
              <div class="col item-container {{task.completed}}">
                MONITOR POST
              </div>
              <div class="col item-container {{task.completed}}">
                {{ task.creator }}
              </div>
              <div class="col item-container {{task.completed}}">
                {{ task.due_date }}
              </div>
            </div>
          {% endif %}
          {% empty %}
            <div class="row">
              <div class="col">
                There are currently no tasks assigned to you.
              </div>
            </div>
          {% endfor %}

        </div>
      </div>
      <!-- end card inner row -->
    </div>

    <!-- Assign by user card -->
    <div class="card" style="padding-bottom:15px;">
      <span>
        <i class="fas fa-spinner card-icon" style="background-color:var(--complete-color);"></i>
        <text class="card-heading">Assigned by You</text>
      </span>
      <br>
      <!-- card inner row -->
      <div class="row">
        <div class="col">

          <!-- Locations Headings -->
          <div class="row">
            <div class="col-2">
              <h6>Project</h6>
              <hr>
            </div>
            <div class="col-3">
              <h6>Post</h6>
              <hr>
            </div>
            <div class="col">
              <h6>Due Date</h6>
              <hr>
            </div>
            <div class="col">
              <h6>Type</h6>
              <hr>
            </div>
            <div class="col">
              <h6>Assigned To</h6>
              <hr>
            </div>
            <div class="col">
              <h6>Due Date / Interact</h6>
              <hr>
            </div>
          </div>
          <!-- End Locations Headings -->

          {% for task in tasks.to_user %}
            <div class="row">
              <div class="col-2 item-container {{task.completed}}">
                {% if task.sample_post %}
                  {{ task.sample_post.project }}
                {% else %}
                  {{ task.live_post.sample_post.project }}
                {% endif %}
              </div>
              <div class="col-3 item-container {{task.completed}}">
                {% if task.sample_post %}
                  {{ task.sample_post.title }}
                {% else %}
                  {{ task.live_post.sample_post.title }}
                {% endif %}
              </div>
              <div class="col item-container {{task.completed}}">
                {{ task.due_date }}
              </div>
              <div class="col item-container {{task.completed}}">
                {% if task.sample_post %}
                  CREATE POST
                {% else %}
                  MONITOR POST
                {% endif %}
              </div>
              <div class="col item-container {{task.completed}}">
                {{ task.assigned_to }}
              </div>
              <div class="col item-container {{task.completed}}">
                {{ task.due_date }}
                {% if task.sample_post %}
                  <i class="fas fa-pencil-alt edit action-link animated item" href="#" style="margin-right: 3px;"></i>
                  <i class="fas fa-trash-alt delete action-link animated item" href="{% url 'marketing:delete_create_post_task' pk=task.pk %}"></i>
                {% else %}
                  <i class="fas fa-pencil-alt edit action-link animated item" href="#" style="margin-right: 3px;"></i>
                  <i class="fas fa-trash-alt delete action-link animated item" href="{% url 'marketing:delete_monitor_post_task' pk=task.pk %}"></i>
                {% endif %}
              </div>
            </div>
          {% empty %}
            <div class="row">
              <div class="col">
                There are currently no tasks assigned by you.
              </div>
            </div>
          {% endfor %}

        </div>
      </div>
      <!-- end card inner row -->
    </div>

  </div>

</div>
<!--  End main page row -->
{% endblock content %}

{% block js %}
<script type="text/javascript">
  $('.assigned-to').click(function() {
    filter_cards([$(this).attr('name')]);
    set_active($(this), 'assigned-to');
  });
</script>
{% endblock js %}